- environment/control.py
- environment/surrogates/chemotaxis_MWC_sensors.py
- environment/surrogates/chemotaxis_minimal.py
- utils/multicell_physics.py
This makes the chemotaxis surrogates work better by over-writing angular velocity in the physics engine. Conserved angular velocity in the physics engine was causing them to get stuck swimming in circles.  This will need to be improved by fine-tuning the physics.
Other minor changes in ```environment/control.py``` and the surrogates improved my ability to debug this problem.
> chemotaxis refinement

- lens/actor/process.py
- lens/boot_compartment.py
- lens/composites/Covert2008.py
- lens/composites/growth_division.py
- lens/environment/boot.py
- lens/environment/lattice_compartment.py
- lens/environment/look_up.py
- lens/processes/CovertPalsson2002_metabolism.py
- lens/processes/CovertPalsson2002_regulation.py
- lens/processes/Endres2006_chemoreceptor.py
- lens/processes/Kremling2007_transport.py
- lens/processes/transport_lookup.py
- lens/utils/rate_law_utilities.py
updaters from #41 are here being applied in the metabolism process, introducing both ```set``` updaters that directly set the reaction flux values rather than passing deltas, and ```accumulate``` updaters that replace the previous method of tracking delta counts with additional  ```__exchange``` key in the state. ```accumulate``` takes the (key, value) passed in update, and adds the value to a key+exchange_key. This is used to pass accumulated delta counts in generate_inner_update, and upon generate_outer update all key+exchange_key are reset to a value of 0.
> apply updaters

- lens/actor/process.py
This PR resolves the situation where multiple updates could apply to the same state keys, and also enables the future ability to roll back state changes. Updates are now accumulated in a copy of the existing state vector and swapped out once all updates are complete.
> Apply all updates to a working state before swapping out with previous state

- lens/actor/process.py
- lens/analysis/analyze_lattice.py
- lens/composites/Chemotaxis.py
- lens/composites/Covert2008.py
- lens/composites/Vladimirov2008.py
- lens/environment/boot.py
- lens/environment/lattice.py
- lens/environment/lattice_compartment.py
- lens/processes/CovertPalsson2002_metabolism.py
- lens/processes/Endres2006_chemoreceptor.py
- lens/processes/Vladimirov2008_motor.py
This PR tunes the chemotaxis composite, which is now fully operational.  There are two processes that go into it: chemoreceptors (Endres & Wingreen 2006) and motor activity (Vladimirov 2008). Each of these processes now has tests, though I still need to add asserts within the test. If the processes are called, they run the test and save output.  
Example output for the chemoreceptor's test:
The composite successfully navigates to regions of higher ligand concentrations. In the ```analyze_lattice``` output shown below, the region of high ligand concentrations is right in the middle of lattice. This behavior still needs to be compared to experimental data and fine-tuned.
The analysis of all states emitted from the chemotaxis composite make the following ```analyze_compartment``` output
> Chemotaxis composite

- lens/environment/boot.py
- lens/processes/membrane_potential.py
- lens/processes/proton_motive_force.py
Here, a membrane potential process is introduced, which is calculated from internal/external concentrations of the ions Na, Cl, K. With this process alone, membrane potential should remain fixed as no ions move across the membrane. A separate process can be used to pump ions across the membrane, for example with ATP synthase, proton pumps, and flagellar activity.
> membrane potential

- lens/processes/Kremling2007_transport.py
- lens/utils/flux_conversion.py
This adds a test to the transport process, and applies the updaters to `set` internal concentrations and `accumulate` external counts.
The test output plots a time series for all relevant states: 
[transport.pdf](https://github.com/CovertLab/Lens/files/3825941/transport.pdf)
> test transport

- lens/actor/emitter.py
- lens/actor/process.py
- lens/analysis/multigen_compartment.py
- lens/analysis/snapshots.py
- lens/composites/Chemotaxis.py
- lens/composites/Covert2002_rFBA.py
- lens/composites/Covert2008_iFBA.py
- lens/composites/growth_division.py
- lens/environment/lattice_compartment.py
- lens/processes/CovertPalsson2002_metabolism.py
- lens/processes/CovertPalsson2002_regulation.py
- lens/processes/Kremling2007_transport.py
- lens/processes/Vladimirov2008_motor.py
- lens/processes/membrane_potential.py
- lens/processes/metabolism.py
- lens/utils/dict_utils.py
Before we were emulating each process as happening simultaneously, with a special kind of process called a "deriver" happening after the other processes. In exploring the problem further, we found instances where we wanted an ordering of things, but for the rest of the processes they can still run with emulated simultaneity. This PR allows us to encode processes as a list of dicts, rather than one dict, which simplifies the process/deriver dichotomy and provides the option during composition to present a series of simultaneous processes, of which derivers need no longer be a special case. This also allows for things like an optimization layer to act on the state changes of the other processes. 
In the meantime I changed the function `dict_merge` to `deep_merge` as this more reflects its …
> Encode processes in layers of simultaneous events rather than one simultaneous event

- README.md
- lens/actor/emitter.py
- lens/actor/process.py
- lens/analysis/run_analysis.py
- lens/analysis/snapshots.py
- lens/analysis/topology.py
- lens/composites/PMF_chemotaxis.py
- lens/composites/Vladimirov2008_chemotaxis.py
- lens/environment/boot.py
- lens/environment/control.py
- lens/environment/lattice.py
- lens/environment/lattice_compartment.py
- lens/processes/Endres2006_chemoreceptor.py
- lens/processes/Kremling2007_transport.py
- lens/processes/derive_volume.py
- lens/processes/membrane_potential.py
This PR moves the chemotaxis composite towards swarming behavior. There are several changes, including a couple bug fixes following the new implementation of process layers (#75).
Changes include:
- a ```PMF_chemotaxis``` composite with added ```transport```, ```volume_deriver```, ```division``` processes. This is a work in progress, and still requires PMF integration
- ```swarm_experiment``` in control. The goal is to place a few chemotactic cells in the center of the environment, and simulate their spread and the formation of chemotactic rings. This experiment creates a hybrid media that supports both transport and chemotaxis processes. A few new options for lattice were also required:
- an option to place cells in lattice at exact locations (the center is used for swarm experiments):
- …
> Towards swarms

- lens/processes/convenience_kinetics.py
- lens/utils/kinetic_rate_laws.py
This introduces a general kinetics process based on convenience kinetics. The process uses the ```kinetics_rate_laws``` util which was originally developed for transport in wcEcoli.  It requires configuration data from ```initial_parameters```, demonstrated in the test with a ```toy_config```:
```
toy_config = {
'reactions': toy_reactions,
'kinetic_parameters': toy_kinetics,
'initial_state': toy_initial_state,
'roles': toy_roles}
```
This process will allow users to quickly configure kinetics, which can be composed with metabolism for flux constraints.  There is still some work to do before composition is quick and easy.
> Convenience kinetics process

- lens/states/chromosome.py
- lens/utils/kinetic_rate_laws.py
This PR introduces a new state class/paradigm, the Datum. It can be instantiated with a dictionary, rendering all the keys in that dictionary as object attributes, operated on, then rendered back to an identical dictionary. This lets you define operations on a more complicated/composite state in object notation, while ending up with the dictionary required for state, database and serialization operations. I provide an example with a working chromosome, composed of datum definitions for its associated genes, domains, transcription factors and rnaps. Several operations are defined on this state including replication initiation, replisome advancement (distributing molecules like transcription factors and rnaps stochastically to the replicating domains), chromosome division and replication …
> Providing Datum class for composite states

- vivarium/composites/kinetic_FBA.py
- vivarium/processes/BiGG_metabolism.py
- vivarium/processes/metabolism.py
The ```kinetic_fba``` composite now only defines regulation logic in string form, and the metabolism process makes the regulation function from this strings.  This keeps parameters simpler -- no functions are passed in, only strings.
> all regulation logic functions handled in metabolism

- project.clj
- setup.py
- vivarium/actor/actor.py
- vivarium/actor/boot.py
- vivarium/actor/control.py
- vivarium/actor/emitter.py
- vivarium/data/knowledge_base.py
- vivarium/environment/boot.py
- vivarium/environment/control.py
- vivarium/environment/look_up.py
- vivarium/environment/make_media.py
While trying to innocuously add an option to specify the mongo host for cloud deployment of the cell shepherd I discovered that providing additional options was not facilitating revision, and in general configuration was over-complicated and with too many ways to specify defaults etc, so I tore it all out and made a general way for configuration to be specified from Control and Command classes. 
There is now a concept of "destinations" where command line arguments are mapped to paths into the configuration dict, so that we can declare where values belong without having to get them all there manually in each control method. Also, all configuration flows from the command line outwards instead of values appearing along the journey as it goes. 
This should allow us to provide the mongo host …
> Reconfiguring configuration

- vivarium/composites/growth_division.py
- vivarium/environment/boot.py
- vivarium/environment/control.py
- vivarium/environment/lattice.py
This fixes some errors arising from the recent configuration revamp in #99.  We really need tests for experiments -- I'll go through and manually test all the experiments tomorrow before merging. ```lattice_experiment``` appeared to working fine with the ```growth_division``` composite, and with the analyses.
@prismofeverything -- I changed ```environment.boot.py``` a bit from what we had discussed today.  Rather than ```initialize_lattice``` and all other initializations receiving and updating ```agent_config```, they receive and update ```boot_config```. This seems cleaner since they don't require ```agent_config```.
The ```growth_division``` composite was eating way too much glucose, so I changed its kinetics. Not sure what happened there, I'll keep an eye out on it.
Some additional …
> Fix experiments and environment boots for new configuration paradigm

- vivarium/actor/process.py
- vivarium/composites/kinetic_FBA.py
- vivarium/processes/BiGG_metabolism.py
- vivarium/processes/metabolism.py
- vivarium/utils/cobra_fba.py
This extends ```cobra_fba``` to utilize the cobra library's MOMA (minimization of metabolic adjustment) option. To turn it on, include ```{'moma': True}``` in ```cobra_fba's``` config -- by default it is kept off.  I have not extensively tested it, but it should help keep flux solutions from jumping around wildly between time steps. This could be useful with dynamical adjusted flux constraints from transport.
> MOMA for cobra_fba

- vivarium/composites/kinetic_FBA.py
clean up ```kinetic_FBA``` composite. This separates the default configs for each process, allowing the composite's ```config``` to specify each process' parameters with a key for that process.  This sets up for parameter scans of the entire composite compartment, which will pass new parameters into the compartment through the ```config```.
> clean up kinetic_FBA

- vivarium/composites/growth_division.py
- vivarium/composites/kinetic_FBA.py
- vivarium/processes/convenience_kinetics.py
- vivarium/utils/dict_utils.py
The convenience process now uses tuples with ('role', 'state') for kinetic parameters rather than strings with 'state_role'. This avoids string manipulation and I find it more elegant.
> convenience kinetics uses tuples rather than strings for role, state

- vivarium/utils/kinetic_rate_laws.py
adds a test to the kinetic_rate_laws utility.  This also helps make sense of the framework, by tracking through how the kinetic rate law is built and executed.
> make a test for kinetic_rate_laws

- vivarium/actor/control.py
- vivarium/environment/control.py
when running experiments, ```actor/control``` was attempting to call the function ```kafka_config()``` instead of the dict ```kafka_config```. The function is now called ```get_kafka_config()```.
> get_kafka_config()

- vivarium/composites/gene_expression.py
- vivarium/composites/gfp_expression.py
- vivarium/data/amino_acids.py
- vivarium/data/chromosome.py
- vivarium/processes/transcription.py
- vivarium/processes/translation.py
- vivarium/states/chromosome.py
- vivarium/utils/datum.py
- vivarium/utils/polymerize.py
This PR introduces a new composite for gene expression, composed of transcription and a new translation process. These processes are linked through a "transcripts" state, which is supplied by the transcription process and subsequently sampled by the translation process. Both processes are essentially the same, being stochastic simulations for binding of polymerases between elongation events. For this reason I abstracted out much of the polymerization code from transcription and the chromosome into the new `polymerize.py`. 
The expression composite behaves in a reasonable way, generating transcripts until nucleotides run out, while also generating proteins from those transcripts until amino acids run out. To run you can type: 
> python vivarium/composites/gene_expression.py
A demonstration …
> Expression composite and abstracting polymerization for translation

- vivarium/actor/actor.py
- vivarium/composites/glc_lct_shifter.py
- vivarium/processes/convenience_kinetics.py
- vivarium/utils/dict_utils.py
This PR introduces the new ```utils/dict_util``` functions ```tuple_to_str_keys``` and the inverse ```str_to_tuple_keys```, which can be used to convert parameters or states that use tuples as keys to string keys.  
Tuples are an attractive way to specify embedded states, especially with roles included -- for example ```('internal', 'g6p_c')``` rather than ```'internal_g6p_c'```. But tuples are not json serializable, which is required by ```actor/actor.py``` in ```encoded = json.dumps(message, ensure_ascii=False).encode('utf-8')``` when Kafka initializes a compartment.
Edit: all tuple to string conversions are now being handled entirely in ```actor/actor.py``` when messages are sent/received.  Thanks everyone for the suggestions.
> Tuple to string keys in actor

- vivarium/composites/glc_lct_shifter.py
- vivarium/composites/master.py
- vivarium/processes/metabolism.py
- vivarium/processes/minimal_expression.py
- vivarium/utils/regulation_logic.py
This PR updates ```utils/regulation_logic.py``` to include thresholds and tuple keys in the string definition.  Strings are JSON serializable, and so they can be passed into compartments, which use ```utils/regulation_logic.py``` to build the regulation functions. 
Here's an example of how to build a function that can be given the current state and returns a Boolean variable: 
> reg_logic = "if not [(external, glc) > 0.1 and (external, lct) < 0.1]"
> reg_function = build_rule(reg_logic)
> reg_boolean = reg_function(state)
The composite ```glc_lct_shifter``` now utilizes this feature by defining regulation logic for LacY expression based on external glucose. The resulting behavior (shown in the attached figure) has LacY inhibited while there is glucose in the environment. Once glucose is …
> Regulation logic thresholds

- vivarium/actor/process.py
The `simulate_process_with_environment` function creates a compartment
with the process and an environment. Then, it simulates running the
process by passing the compartment to `simulate_with_environment`.
This function can be used to replace redundant code across many
processes' test functions.
> Create Function to Simulate Process in Environment

- vivarium/environment/control.py
this corrects the config sent by ```environment/control's``` ```init_experiments()```, which was introduced in #119.
> correct config in init_experiment

- vivarium/environment/lattice.py
- vivarium/processes/metabolism.py
Fix the pytest errors coming from metabolism and lattice.  Mostly, I failed to provide test configs. Metabolism's toy_config had opposite signs on its exchange bounds.
> fix all pytest errors

- requirements.txt
- vivarium/actor/process.py
- vivarium/composites/gene_expression.py
- vivarium/composites/gfp_expression.py
- vivarium/data/chromosome.py
- vivarium/processes/degradation.py
- vivarium/processes/transcription.py
- vivarium/processes/translation.py
- vivarium/utils/datum.py
- vivarium/utils/polymerize.py
This PR converts the binding affinities from static values for each promoter to a dynamic value based on the existing concentrations of relevant transcription factors. Affinities are indexed by a tuple which has one element for each binding site, in addition to the promoter id. In the absence of concentrations, these binding site states are `None`, but as the concentration rises if a configured threshold is passed that state becomes identified with the transcription factor id, which then provides a new index into the binding affinities mapping.
> Base binding affinities on transcription factor states

- vivarium/actor/composition.py
- vivarium/actor/process.py
- vivarium/composites/PMF_chemotaxis.py
- vivarium/composites/gene_expression.py
- vivarium/composites/growth_division.py
- vivarium/composites/master.py
- vivarium/composites/ode_expression.py
- vivarium/composites/simple_chemotaxis.py
- vivarium/composites/variable_flagella.py
- vivarium/processes/Endres2006_chemoreceptor.py
- vivarium/processes/Kremling2007_transport.py
- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/Vladimirov2008_motor.py
- vivarium/processes/convenience_kinetics.py
- vivarium/processes/degradation.py
- vivarium/processes/derive_concentrations.py
- vivarium/processes/derive_counts.py
- vivarium/processes/derive_globals.py
- vivarium/processes/division.py
- vivarium/processes/growth.py
- vivarium/processes/membrane_potential.py
- vivarium/processes/metabolism.py
- vivarium/processes/minimal_expression.py
- vivarium/processes/ode_expression.py
- vivarium/processes/template_process.py
- vivarium/processes/transcription.py
- vivarium/processes/translation.py
- vivarium/processes/transport_lookup.py
- vivarium/utils/dict_utils.py
This begins the transition to the schema framework, in which states have a schema for updaters, units, and division. These specify how to update those states, what units are expected (which will also allow us to keep units within the states), and how to divide them upon division.  I'm pacing myself by putting updaters in first. Once all the updaters are working, I'll add in units and division to the schema in a separate PR.
> state schema

- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/ode_expression.py
minor tweak to initialize flagella concentrations in ode_expression in addition to counts. We will need a better way to initialize counts/concs if one is provided but not the other.
> initialize flagella concentrations

- vivarium/environment/lattice.py
- vivarium/utils/multicell_physics.py
this adds the option for lattice to use the pygame option in ```multicellular_physics```, which supports live visualization of the cells as the move, grow, and divide in the physics engine.  This helped me debug jitter to support more torque.
> multicell physics debug with pygame

- vivarium/actor/process.py
- vivarium/processes/metabolism.py
This PR initializes metabolism's internal pools to match the initial cell mass -- ridding the model of all unaccounted for "dark mass" upon initialization.
> Initialize internal pools by mass

- vivarium/actor/boot.py
- vivarium/environment/boot.py
- vivarium/environment/lattice.py
This PR adds the option to set ```emit_frequency``` in ```lattice```. Up to now, we have been emitting the fields and agent locations at every time step; this results in a large amount of data in the database, much of it redundant between time steps.  Reducing the frequency of emits will reduce the memory load on the DB and reduce analysis run time.
> emit frequency in lattice

- vivarium/compartment/composition.py
- vivarium/compartment/process.py
- vivarium/composites/PMF_chemotaxis.py
- vivarium/composites/gene_expression.py
- vivarium/composites/growth_division.py
- vivarium/composites/master.py
- vivarium/composites/ode_expression.py
- vivarium/composites/simple_chemotaxis.py
- vivarium/composites/variable_flagella.py
- vivarium/environment/lattice_compartment.py
This PR moves ```schema``` from ```Compartment``` to ```Store``` and introduces a test for ```lattice_compartment```.  ```schema``` defines properties of state variables such as dividers, updaters; units and mass are coming soon.  As such, it is a better fit in Store, which contains the state variables.  One simplification has ```initialize_state``` get the schema with ```get_schema```, rather than having schema created within the composite functions.  The test in ```lattice_compartment``` makes a simple compartment that includes a ```divide_condition```; this allowed me to test that dividers are working properly
> Schema in Store

- vivarium/analysis/motor.py
- vivarium/environment/control.py
- vivarium/environment/lattice_compartment.py
This PR changes how experiments are configured in ```environment/control```, to support multiple agent types.  Previously the experiment included one ```agent_type``` and a ```number``` for how many of them were added.  Now ```agents``` is a dict with ```{agent_type: number}```, and the function ```init_experiment``` boots each one. 
```chemotaxis_experiment``` uses this to boot one chemotaxis agent, and one motor agent.
> multiple agent types in experiment

- vivarium/actor/outer.py
- vivarium/compartment/process.py
- vivarium/composites/simple_chemotaxis.py
- vivarium/environment/boot.py
- vivarium/environment/control.py
- vivarium/utils/multicell_physics.py
I was reworking ```minimal_chemotaxis``` following the recent update to ```multicellular_physics``` in #151, and came upon a few bugs that are fixed here.  The t_exchange for chemotaxis agents needs to be fairly short, to support the high level of coupling between cell and environment. Previously, it appears we were assuming integer time steps in ```outer```.  Also, Store's schema was assuming all states with schema are in the initial_state -- not true, and now fixed.
> debugging chemotaxis

- vivarium/processes/diffusion.py
This adds a diffusion process that can do 1D and 2D spatial diffusion with arbitrary membranes that have configurable channels/pores. This is the first process that allows for dynamic ports -- each location in the spatial grid gets its own port, with a key set by its coordinate (```(0,0)```, ```(0,1)```, etc). These ports can be connected to ```Stores``` such as ```environment``` or ```internal```.
The most basic application addresses #156. You can make a grid with 2 location s, and a membrane between them. One location will be connected to the environment store, the other to the internal store. Diffusion through the membrane is determined by channels' concentrations and diffusion constant:
A more complex example shows off a 2D grid with membranes:
> Diffusion process

- vivarium/compartment/composition.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/diffusion_network.py
This PR adds a ```diffusion_field``` process, which supports 2D field-based diffusion as is used by ```lattice``` -- thus taking a step towards modularizing lattice and making it into a compartment. 
This process contrasts with the existing ```diffusion_network```, which is a more general diffusion process that implements fields as networks with locations as nodes and adjacency as edges -- this allows for the addition of membranes along these edges, and can also support arbitrary topologies.
```diffusion_nework``` is now only a grid-based network through configuration, by default it just requires nodes and edges, and so can be configured to any topology.
This is the output for a diffusion network with two locations, and an edge between them that has a membrane.
This is the output for a …
> Diffusion field

- vivarium/processes/diffusion_field.py
- vivarium/processes/diffusion_network.py
- vivarium/processes/multibody_physics.py
This PR continues the modularization of ```lattice's``` processes with a multibody physics process, ```multibody_physics```. There is still a lot of work left to do on this, but with this PR bodies can be initiated in the space, and run with pymunk. Each body gets its own port, with keys for location, angle, volume, mass, and motile forces -- to add and remove bodies will requires us to add and remove ports.
There is a basic test function and plotting that creates this output:
```diffusion_field``` is also updated to support exchange bodies.  This uses a dictionary of body_ids paired with locations and exchange.  With each update, the exchanges are added at the given locations, and then diffusion runs. This can be seen with the constant secretion of a molecule in this test:
TODO -- …
> multibody physics process

- vivarium/composites/lattice_environment.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/multibody_physics.py
This moves some of the code developed in #169, so that it can be merged into master before that more involved branch gets merged in.
The changes included here have the environment processes connect to agents through individual ports, rather than all of them through the same ```agents``` port.  This is necessary, since when we compose the environment with actual agents, they will each have their own ```Store``` for their boundary states. And so the environment will require an individual port to each of these ```Stores``` to receive updates.
> agent ports

- vivarium/composites/lattice_environment.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/multibody_physics.py
This reverts some of the work from #171, back to having all agent states under one ```port``` in the environmental compartments.  After discussion with @prismofeverything, we decided to keep a ```ports``` static, and have the ```Stores``` handle all the dynamics resulting from a changing number of agents. This will likely require Stores to have many different keys, one for each agent, so that agents can share a "Boundary" Store that connects up to the environment compartment's ```'agents'``` ```port```.
> Agent states under one port

- vivarium/processes/degradation.py
The degradation process's default settings were too small for any
changes to be observed when the test was run. This commit raises those
counts so the test shows changes. This leads to output plots like this:
> Raise Degradation Default Settings to Show Change

- vivarium/compartment/composition.py
- vivarium/composites/lattice_environment.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/multibody_physics.py
This completes the transition begun in #167. ```convert_to_timeseries``` is now removed from ```composition.py```, so there is no redundant code left. All compartment simulations are using the ```TimeseriesEmitter``` for their timeseries.
> complete timeseries emitter conversion

- requirements.txt
- vivarium/compartment/composition.py
- vivarium/composites/PMF_chemotaxis.py
- vivarium/composites/chemotaxis_master
- vivarium/composites/flagella_expression.py
- vivarium/composites/variable_flagella.py
- vivarium/processes/Mears2014_flagella_activity.py
This PR begins the chemotaxis master composite, ```chemotaxis_master```, which will be used for the final story of the vivarium paper and for the chemotaxis paper.
The most exciting addition is the new ```plot_compartment_topology``` plotting function in ```composition.py```. This adds ```networkx``` to our requirements -- a popular library for network analysis that we can probably use elsewhere. ```plot_compartment_topology```  takes in a compartment and saves a network figure of its topology. This is useful for quickly assessing complex topology structure.
chemotaxis master is the only composite currently using it, but it can be added to all composites with:
```plot_compartment_topology(compartment, out_dir)```
> begin chemotaxis master, add topology plot

- vivarium/compartment/process.py
- vivarium/composites/lattice_environment.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/multibody_physics.py
I'm again redoing the agent port for the environmental compartments. There is now only one key in the agent ports: ```['agents']```. Under this key is a dict with all agent ids matched to their boundary states. This way, the keys don't need to be updated as agents are added/removed from boundary stores.
> agent port with agent key

- vivarium/compartment/process.py
- vivarium/composites/lattice_environment.py
- vivarium/processes/multibody_physics.py
This updates the snapshots plot in ```multi body_physics``` to include fields. 
I realize there is a ```snapshots``` plot in ```analyses``` that does pretty much the same thing, but that one is done through the database querying. In general, there are many plot functions accumulating in individual processes that are almost like analyses, but they are much easier to use and more useful! We might need to be a rethink of how these can be used and perhaps merged with analyses.
> make snapshot plot with fields

- vivarium/composites/growth_division.py
- vivarium/composites/lattice_environment.py
This refactor breaks up the ```get_composite``` function for ```growth_division``` and ```lattice_environment``` into two steps: 1) ```get_compartment``` gets the ```processes``` and ```topology```, ```get_composite``` takes those, creates derivers and stores for them, and compartment options. Separating out the process/topology from the rest will be useful when hooking up environment compartments with agent compartments.
> Separate compartment from get_composite

- vivarium/composites/chemotaxis_master
Now that we have separate timescales for processes, metabolism can be added to ```chemotaxis_master```.  It worked beautifully, with metabolism running 1 time per second, and flagella every 0.01 seconds. 
Here is ```chemotaxis_master's``` new topology:
> bring metabolism back into chemotaxis master

- vivarium/parameters/parameters.py
This gives ```parameters``` an upgrade, and fixes the example scan to use the newest version of ```master```.
changes include:
- a new ```get_parameters_logspace(min, max, number)``` lets you define a logspace for your parameter scan.
- if the scan's defined ```output_value``` for evaluation is not available in the simulation output, a message is printed to inform the user and that value is set to ```None```.
Here is the output of scanning master's glucose transport k_cat. Growth rate goes up as the k_cat increases!
> improve parameter scan

- vivarium/compartment/composition.py
- vivarium/compartment/process.py
- vivarium/processes/derive_concentrations.py
- vivarium/processes/derive_counts.py
- vivarium/processes/derive_globals.py
- vivarium/processes/derive_mass.py
This PR cleans up some of the derivers and ```get_derivers``` in ```composition```.  The individual derivers have new asserts to check that the assigned ports are corrects.  ```derive_globals``` no longer handles growth_rate -- derivers should not count on time step, and growth rate should be more of an outcome of a simulation than a state anyways. ```derive_globals``` now calculates length -- this can be used in the boundary store for the environment to use, rather than have the environment calculate length from volume.
> Deriver cleanup, asserts, length

- vivarium/environment/boot.py
- vivarium/environment/control.py
This updates the agent initialization function in ```environment.boot``` to include derivers.  This should have been included in #183. Note to self -- tests would have helped catch this earlier!
> Rehab experiments

- vivarium/compartment/composition.py
- vivarium/composites/glc_lct_shifter.py
- vivarium/composites/txp_mtb_ge.py
- vivarium/environment/lattice_compartment.py
- vivarium/processes/cellular_potts.py
- vivarium/processes/convenience_kinetics.py
- vivarium/processes/degradation.py
- vivarium/processes/derive_globals.py
- vivarium/processes/derive_mass.py
- vivarium/processes/metabolism.py
This PR does two things:
1. ```get_derivers``` is refactored. 
- I separated out a function ```get_deriver_config_from_proceses``` that takes a process list and makes a deriver config and topology. 
- ```get_derivers``` calls this function, and updates the config with passed-in values, and then makes the derivers. This lets users configure derivers without needing to declare them in process.  
- The global deriver (```derive_globals```) is no longer automatically inserted. It has to be called by a process' ```deriver_settings``` if required, or passed in as a config to ```get_derivers```. Two processes required updated ```deriver_settings``` -- ```convenience_kinetics``` and ```degradation```.
2. The mass deriver, ```derive_mass``` can be initialized with "dark mass".  This is mass that …
> get_deriver refactor and dark mass

- vivarium/processes/multibody_physics.py
This PR adds:
1. a ```mother_machine``` config option to the multibody process, 
2. a growth_division test.
3. an additional ```animate``` option, that supports interactive Matplotlib figure when multibody is runninng.
Here is a screenshot of of the mother machine config in action:
> Mother machine

- vivarium/processes/multibody_physics.py
This fixes a bug I was having only when debugging with pygame. The jitter force was not scaling correctly, the fix was easy -- I had to use the ```pygame_scaling``` factor for forces as well.  
While at it, I made the mother_machine more configurable, with adjustable channel widths/height.
> more multibody/ mother machine

- vivarium/compartment/composition.py
- vivarium/composites/flagella_expression.py
- vivarium/data/chromosomes/flagella_chromosome.py
- vivarium/processes/Mears2014_flagella_activity.py
This PR includes several tweaks for the analysis and visualization of flagella.
1. Most importantly, the ```flagella_expression``` composite's initial ribosome, RNAP, and base pair counts are bumped up one order of magnitude to get ~8 flagella expressed per cell cycle (1st fig below).
2. Some tweaks to the listed gene order in the ```flagella_chromosome``` orders the just-in-time expression plot.
3. Tweaks to ```composition's``` ```plot_simulation_output``` handle non-numeric states better. It does not plot them, but accounts for them when setting up the different plot columns.
4. ```Mears2014_flagella_activity``` process has an analysis that shows flagella activity upon adding new flagella (2nd fig below).
> Variable flagella

- vivarium/compartments/chemotaxis_master.py
- vivarium/compartments/chemotaxis_minimal.py
- vivarium/compartments/lattice.py
- vivarium/compartments/transport_metabolism.py
- vivarium/core/composition.py
- vivarium/core/emitter.py
- vivarium/library/dict_utils.py
- vivarium/library/pymunk_multibody.py
- vivarium/plots/Mears2014_flagella_activity.py
- vivarium/plots/metabolism.py
- vivarium/processes/Endres2006_chemoreceptor.py
- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/antibiotic_transport.py
- vivarium/processes/convenience_kinetics.py
- vivarium/processes/homogeneous_environment.py
- vivarium/processes/membrane_potential.py
- vivarium/processes/metabolism.py
- vivarium/processes/ode_expression.py
- vivarium/processes/one_dim_environment.py
- vivarium/processes/timeline.py
Here is another step in the migration towards the new tree framework. Timeline and 1D_environment are now processes that can be composed with the main processes before running an experiment.  Timeline introduces pre-set perturbations through different ports throughout the simulation.  1D_environment mimics an environment of pre-set volume. These processes are configured and composed in ```composition.py```, under ```process_in_experiment``` or ```compartment_in_experiment```. 
config for a timeline. timelines are lists of tuples: [(time, {(path, to, variable): value})]. ports are where the timeline gets plugged in.
```
'timeline': {
'timeline': [(100, {
('environment', 'glc__D_e'): 3.0,
('environment', 'lcts_e'): 3.0,}),
'ports': {'external': ('boundary',)}},
```
config for a 1D …
> 1D env process for simulation, rework emitter timeseries output

- vivarium/compartments/lattice.py
- vivarium/compartments/static_lattice.py
- vivarium/core/emitter.py
- vivarium/core/experiment.py
- vivarium/experiments/chemotaxis_master.py
- vivarium/experiments/chemotaxis_minimal.py
- vivarium/library/pymunk_multibody.py
- vivarium/plots/multibody_physics.py
- vivarium/processes/Endres2006_chemoreceptor.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/metabolism.py
- vivarium/processes/multibody_physics.py
- vivarium/processes/static_field.py
- vivarium/processes/translation.py
Here we add a new process ```static_field```, which calculates an agent's local environment with a function (exponential, linear, or gaussian), rather than lookup from saved numpy array. This assumes no diffusion -- the fields remain constant. This saves us from having to handle the large arrays, and gives more continuous values. The process is used in a ```static_lattice``` compartment, which can be used in chemotaxis experiments.
There are a number of additional changes.
- the chemoreceptors are again initializing at a steady state by calling ```run_to_steady_state()``` in the constructor.
- ```chemotaxis_master``` experiment gets all of the expected external states out of the agent, and uses it to initialize the lattice fields (too many fields! this is why I made the static_field for …
> Static Field

- vivarium/core/emitter.py
- vivarium/core/experiment.py
- vivarium/core/repository.py
- vivarium/experiments/mother_machine.py
- vivarium/processes/diffusion_field.py
This brings back the ```DatabaseEmitter```, which saves experiment emissions to mongodb.  In order to get numpy arrays in there, we also now have serializers in the Store, and a serializer_library in ```repository```. The only serializer in the library is ```'numpy'``` -- this can be extended to whatever serializers we need in the future.
> DB emitter and serializer

- vivarium/compartments/master.py
- vivarium/compartments/transport_metabolism.py
- vivarium/core/composition.py
- vivarium/core/experiment.py
- vivarium/parameters/parameters.py
This PR rehabilitates the ```parameter_scan``` in ```parameters.py``` to use the new compartment object.  Parameters are passed in through ```compartment.generate```, and conditions through experiment's ```initial_state```.  
I added a test for parameter scanning, which uses a toy model with a ```ConvenienceKinetics``` process. The test scans a k_cat in 3 different conditions, and measures the resulting flux.  The resulting output looks like this:
> Parameter scan with compartment

- vivarium/experiments/mother_machine.py
- vivarium/library/pymunk_multibody.py
- vivarium/plots/multibody_physics.py
- vivarium/processes/multibody_physics.py
This rehabilitates the ```mother_machine``` experiment: ```snapshots``` plot is now using lists of lists for the fields (the numpy serializer is doing its job and serializing numpy arrays, but not yet de-serializing).  And the ```pymunk_multibody``` library is setting a different thickness for the barriers between mother machine channels -- I had set the thickness of the external barrier really high to avoid chemotaxis agents slamming through barriers, and this unintentionally made the mother machine barriers thick as well..
> Fix mother machine

- vivarium/core/experiment.py
- vivarium/processes/transcription.py
- vivarium/processes/translation.py
Calling set operators on the result of dict.keys(), e.g.
```
dict.keys() & someSet
```
fails in Python 2. This commit fixes all such patterns in the code base
based on a search for the substring `.keys()` in `/vivarium/`.
I'm working on setting up GitHub actions to run our unit tests continuously in py2 and py3 so we don't run into any more issues like this
> Fix Use of Set Operators on dict.keys()

- vivarium/core/experiment.py
- vivarium/core/repository.py
Dividers already work for individual values, but a need arose for dividing a collection of entities specified by a `*` schema, essentially splitting them up between the daughters. This PR shifts the special `_divider` key out of `schema_keys` (which means it does not necessarily denote a leaf) and now supports operation at any point in the tree. 
Tested using @eagmon's `split_dict` divider which now works for the quarks example at least. One test is failing (injector.py) but it is failing in master also? So, should be good to go.
> Specify divider for branches

- vivarium/core/experiment.py
- vivarium/library/dict_utils.py
Consider the case when we are using `inverse_topology` to get the
absolute form of an update with two ports, `global` and `port`. Say the
topology maps `global` to `boundary` and `port` to
`('boundary', 'store')`. Before this commit, if inverse_topology handled
`port` and then `global`, it would first create a dictionary with the
value of `port` at `('boundary', 'global', 'store')`. However, next when
handling `global`, it would overwrite `store` with the value of `global`
instead of merging the dictionaries.
This commit fixes `assoc_path` and creates a test to check for any
regressions.
> Fix Bug in assoc_path

- .github/workflows/pytest.yml
- vivarium/library/pretty.py
This sets up continuous integration with GitHub Actions to run pytest on all commits to `master` and all PRs to `master` to make sure we don't break anything moving forward. Right now it only tests Python versions 3.6, 3.7, and 3.8 because the tests fail on older Python versions
> Continuous Integration

- local/draw_pygame.py
- vivarium/library/pymunk_multibody.py
- vivarium/processes/multibody_physics.py
This adds ```segment``` and ```circle``` agent shapes to ```multibody_physics```, in addition to the previous ```rectangle```. Agent shapes can be set by the argument ```agent_shape``` in ```multibody_physics```. All agents in a given simulation take the same shape once it has been set. The default is now ```segment```, since it is the closest to E. coli's true shape (see figure below).
- Additionally, all trace of pygame has been removed from ```pymunk_multibody``` library, and for debugging with pygame there is now a ```draw_pygame``` file under the directory ```local.
- I also added a docstring to ```multibody_physics``` process in the style of @U8NWXD!
> Agent shapes

- vivarium/library/pymunk_multibody.py
- vivarium/processes/multibody_physics.py
In #254 I added a segment shape to multibody, which better approximates e coli shape.  Segments have two endpoints and a radius. The radius gives the cells width, and also wraps around the endpoints to give that rounded edge. But they add an additional radius*2 to the length of the segment in doing so. Here, length=length-width makes the total length of the cell shape match the provided length and thus removes artifacts seen in #257.
> fix segment shape in pymunk

- vivarium/compartments/antibiotics.py
- vivarium/core/composition.py
- vivarium/core/experiment.py
This PR introduces an interface for asynchronous processing of process update invocations and an implementation using python 3's multiprocessing library. This same interface can be used for distributed computing as well (but requires an implementation). 
The main gist of this is that instead of computing the update directly, we create an object that represents the deferred execution, then call `get()` on that object when we need the value. In the original synchronous case this returns immediately, but in the asynchronous case these functions get sent to the multiprocessing `Pool` and only block when `get()` is called. This let's all of the updates that can be computed this time step compute in parallel, and the experiment applies these updates in the usual way. 
The main constraint is …
> Multiprocessing for process updates

- vivarium/core/experiment.py
- vivarium/core/process.py
- vivarium/core/registry.py
MongoDB doesn't understand numpy scalars, so we need to transform them
into ints and floats before emitting them. We add functionality to the
serializers to handle numpy scalars and use them when emitting data.
> Serialize Emitted Data for Pymongo

- vivarium/analysis/analyze.py
Now that the tags plot expects a full path to the tagged molecule, we
need to change the analysis script accordingly. Here we do so. This also
requires that the CSV of tagged molecules be updated to include as the
first item of every row the store (`boundary`) to access.
> Fix Analysis Script to Match Tags Plot

- vivarium/processes/metabolism.py
this makes the metabolism declare '_value' of the internal metabolites, overriding any defaults.
> set the values of metabolites in metabolism

- vivarium/compartments/flagella_expression.py
- vivarium/core/composition.py
- vivarium/data/nucleotides.py
- vivarium/data/synonyms.py
- vivarium/experiments/lattice_experiment.py
- vivarium/processes/agent_names.py
- vivarium/processes/degradation.py
- vivarium/processes/metabolism.py
- vivarium/processes/transcription.py
- vivarium/processes/translation.py
We were previous using ATP, but not producing ADP in the expression processes' ATP hydrolysis reactions.  This is corrected.  Also, the ```Flagella_expression_metabolism``` compartment, which was previously using ```gene_expression``` compartment and doing an awkward merge with ```metabolism``` and ```convenience_kinetics``` for transport, is now just declaring the full compartment without using ``` gene_expression```.
```Flagella_expression_metabolism``` compartment has some poor behavior upon division that I still need to work out before this merges.
> ADP from ATP hydrolysis in expression processes

- vivarium/library/units.py
When Pint deserializes unit or quantity objects, it uses the application
registry. Here we set our units registry to be the application registry
so that deserialized units are compatible with other units.
This change is required for parallel processing to work.
> Set Pint Application Registry

- vivarium/core/experiment.py
The parallel processing code was trying to call `.end()` on the path instead of the process
> Bugfix in parallel processing

- vivarium/core/composition.py
- vivarium/core/experiment.py
- vivarium/core/process.py
- vivarium/processes/death.py
Fixing the death process to correctly target processes to remove also required changing `update_in` to support empty paths, which should be interpreted as referring to the root of the dictionary.
> Fix Death Process

- vivarium/processes/diffusion_cell_environment.py
The CellEnvironmentDiffusion process used to implicitly assume a
timestep of 1 second by not using the timestep parameter. Here we fix
that by multiplying the rates by the timestep.
> Fix Cell-Environment Diffusion to Use Timestep
