- analysis/location_trace.py
- environment/boot.py
- environment/control.py
- environment/surrogates/chemotaxis_MWC_sensors.py
- environment/surrogates/chemotaxis_minimal.py
- reconstruction/kinetic_rate_laws/parameters/example_parameters_4.json
- reconstruction/kinetic_rate_laws/rate_law_utilities.py
This fixes chemotaxis_MWC surrogate to boot appropriately, and minor tweaks to improve its behavior.
> Chemotaxis_MWC tweaks

- lens/environment/boot.py
The new ```wrap_boot_environment``` function enables simpler environment definitions, with less repeated code.
> make a wrap_environment_boot function, to remove repeated code

- lens/environment/boot.py
- lens/processes/CovertPalsson2002_metabolism.py
- lens/processes/Vladimirov2008_motor.py
- lens/utils/make_network.py
This addition saves metabolism's stoichiometric network when the metabolism process is run on its own.  The network is a bipartite graph, with reactions and molecules as nodes. The output files, ```nodes.csv``` and ```edges.csv``` can be opened and examined by any network visualization software. This will allow easier analysis of metabolic flux.
The screenshot below shows the metabolic network as viewed in Gephi:
> Metabolism analysis

- lens/processes/template_process.py
adds a template for new processes, with all of the required functions.
> template for processes

- lens/environment/README.md
- lens/environment/make_media.py
This PR adds a test for ```make_media```, which executes several operations including ```get_saved_media()```, ```make_recipe()```, ```combine_media()```, ```grammar.parse()``` ```make_timeline()```.
> test make_media

- lens/actor/emitter.py
- lens/actor/outer.py
- lens/analysis/analysis.py
- lens/analysis/analyze_lattice.py
- lens/analysis/chemotaxis_trace.py
- lens/analysis/multigen_compartment.py
- lens/analysis/run_analysis.py
- lens/analysis/snapshots.py
- lens/composites/growth_division.py
- lens/environment/boot.py
- lens/environment/control.py
- lens/environment/lattice.py
- lens/environment/lattice_compartment.py
- lens/processes/Vladimirov2008_motor.py
- lens/processes/protein_expression.py
Several new features introduced here, all within the domain of tracking phylogenies and tagging proteins for analysis purposes. These are illustrated with the new analysis plots.
A multigen plot shows the state of compartments over multiple generations. Here showing the state of a single low-expressed protein:
The snapshot figure traces the phylogenies by adding mutations to the color with every generation. You can see a red lineage set itself apart from the rest of the population:
Tagged proteins shown with a bright green. This are the same protein shown in the multigen plot:
Also, ```location_trace``` now has a legend:
> Trace phylogeny and tag proteins

- lens/analysis/snapshots.py
- lens/environment/control.py
minor changes to the snapshots analysis
> clean up snapshots for ecoli and cdsA

- lens/processes/CovertPalsson2002_metabolism.py
- lens/processes/CovertPalsson2002_regulation.py
This adds a test for the regulation process. If directly called, the process file runs a simulation with a timeline, and plots the resulting behavior: 
[covert2002_regulation.pdf](https://github.com/CovertLab/Lens/files/3821296/covert2002_regulation.pdf)
> Regulation test

- lens/analysis/analyze_lattice.py
- lens/analysis/chemotaxis_trace.py
- lens/analysis/location_trace.py
- lens/analysis/run_analysis.py
- lens/analysis/snapshots.py
- lens/environment/boot.py
- lens/environment/control.py
- lens/environment/lattice.py
- lens/processes/CovertPalsson2002_metabolism.py
- lens/processes/CovertPalsson2002_regulation.py
- lens/processes/Endres2006_chemoreceptor.py
- lens/processes/Kremling2007_transport.py
- lens/processes/Vladimirov2008_motor.py
- lens/processes/membrane_potential.py
- lens/processes/metabolism.py
- resources/public/js/lens.js
This makes some progress towards a lattice with different x and y edge lengths. This allows for experiments such as shown below.  This will be useful for chemotaxis experiments, where we can place cells at one end and drop an attractant at the other end.
An example locations plot after these changes:
An example snapshots plot after these changes:
> Long lattice

- lens/processes/membrane_potential.py
This PR extends the ```membrane_potential``` process to include delta_pH and the proton motive force (PMF). It also makes the process configurable, and adds more data and references.
> proton motive force

- lens/analysis/snapshots.py
- lens/environment/control.py
- lens/environment/lattice.py
- lens/processes/Vladimirov2008_motor.py
This PR includes several tests for motility, both in ```lattice``` and in ```Vladimirov2008_motor```. These tests are both useful for running pytest, and for tuning parameters.  Lattice is looking pretty good -- forces applied in there result in behavior that matches expectation. The motor process requires some work -- the observed run/tumble lengths are greater than expected from experimental measurements.
Lattice tests, with placing a body in the physics and applying forces to it corresponding to run and tumble:
Motor tests:
with a fixed chemoreceptor state:
scanning the chemoreceptor state, ```P_on```:
> Motor tests

- lens/utils/kinetic_rate_laws.py
A few small changes:
* A static value was being calculated inside a generated function, I moved it outside of the generated function so it only needs to be calculated once (`construct_convenience_rate_law`)
* Some no-argument functions were being generated then called for their value, this can be simplified to a simple function call (`cofactor_*ator`)
* I reordered the functions to be introduced in order of reference. I know python lets you put functions anywhere and it will find them, but I still find helpful for overall logical flow of the code to have functions referenced by other functions defined before those functions (`get_molecules`)
> Small cleanup and reorganization of kinetic rate laws function generation

- lens/analysis/snapshots.py
further cleaning up the snapshot analysis:
> one colorbar per field snapshots

- vivarium/analysis/location_trace.py
- vivarium/analysis/motor.py
- vivarium/analysis/run_analysis.py
- vivarium/processes/Endres2006_chemoreceptor.py
- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/convenience_kinetics.py
- vivarium/processes/metabolism.py
This PR cleans up some of the figures in the process tests and analysis, in preparation for the poster presentation at build-a-cell.
> clean up figures

- vivarium/actor/process.py
- vivarium/composites/gene_expression.py
- vivarium/composites/gfp_expression.py
- vivarium/data/chromosome.py
- vivarium/processes/degradation.py
- vivarium/processes/deriver.py
- vivarium/processes/transcription.py
- vivarium/processes/translation.py
- vivarium/states/chromosome.py
- vivarium/utils/polymerize.py
Here is a simple process to get transcripts degrading using first-order Michaelis-Menten kinetics. When composed with the rest of the expression composite we see transcripts going down as well as up, as well as nucleotides being reintroduced after degradation:
> Process for transcript degradation

- vivarium/actor/process.py
- vivarium/composites/PMF_chemotaxis.py
- vivarium/composites/glc_lct_shifter.py
- vivarium/composites/growth_division.py
- vivarium/composites/master.py
- vivarium/composites/ode_expression.py
- vivarium/composites/variable_flagella.py
- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/convenience_kinetics.py
- vivarium/processes/metabolism.py
- vivarium/processes/ode_expression.py
This adds ```ode_expression``` to the composite ```PMF_chemotaxis```, which expresses flagella. The flagella counts are linked to the flagella process ```Mears2014_flagella_activity```, and so as the flagella count changes, the flagella activity is affected.
A couple of clean ups are also rolled into this PR. I've begun migrating a processes configurations into those processes, with functions for ```get_configuration()``` that can be imported by other processes/compartments. For example, the ```PMF_chemotaxis``` composite imports ```get_flagella_expression()``` and ```get_e_coli_core_config()```, which allows it to apply specific configurations.
> Flagella ode expression composed with flagella activity

- vivarium/environment/lattice_compartment.py
#134 left out derivers from basic_compartments. Adding them in here.
> add derivers to basic compartments

- vivarium/processes/derive_globals.py
- vivarium/processes/metabolism.py
I will keep this PR open for a while as I catch more fixes to the new deriver processes.
> more deriver updates

- vivarium/composites/glc_lct_shifter.py
- vivarium/environment/control.py
- vivarium/processes/convenience_kinetics.py
- vivarium/processes/metabolism.py
- vivarium/processes/ode_expression.py
add a plot called ```plot_diauxic_shift``` to ```glc_lct_shifter``` for analyzing test output.
> Diauxie plot

- vivarium/analysis/analyze_compartment.py
- vivarium/compartment/composition.py
- vivarium/compartment/process.py
- vivarium/composites/simple_chemotaxis.py
- vivarium/environment/boot.py
- vivarium/environment/control.py
- vivarium/environment/lattice.py
- vivarium/processes/Endres2006_chemoreceptor.py
- vivarium/processes/Vladimirov2008_motor.py
this PR cleans up some processes and experiments for chemotaxis, along with minor changes that allow for improved testing, and refactoring of ```lattice``` emit calls.
> Chemotaxis clean up

- vivarium/compartment/process.py
- vivarium/composites/lattice_environment.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/multibody_physics.py
```lattice_environment``` is a new composite that integrates ```multibody_physics``` (#163) with ```diffusion_field``` (#161) to make a full lattice environment compartment, with agent bodies that move around based on the multi body physics, and exchange molecules with the field based on their locations.
```multibody_physics``` now has a single port, ```bodies```, which has all of the individual agent bodies as variables with their own dictionary for location, angle, etc.  These are updated via a new ```merge``` updater. This allowed for simpler composition, with both ```multibody_physics``` and ```diffusion_field``` plugging into the same ```bodies``` store.  We'll see if these needs to be changed as agent are added/removed throughout a simulation.
> Lattice Environment Composite

- vivarium/processes/Mears2014_flagella_activity.py
This updates the ```Mears2014_flagella_activity``` process to vary motile force with number of flagella.  The force of 25 pN per flagella comes from (Berg H. "E. coli in motion". 2004)
The bottom subplot of this figure shows the total motor thrust adjust as flagella are added/removed. Note - motile state also changes thrust level:
> vary motile force with number of flagella

- vivarium/data/synonyms.py
- vivarium/processes/cellular_potts.py
- vivarium/processes/metabolism.py
- vivarium/utils/make_network.py
To start off the effort of measuring energy use, I made a plot for energy use in metabolism: 
While at it in metabolism, I restored the ```make_network``` utility to view metabolism's stoichiometry with Gephi -- a network visualizer. The screenshot below shows the BiGG model iAF1260b, with edge width (which you can't really see in this image) given by fluxes in a short metabolism simulation:
> Energy plot

- vivarium/processes/metabolism.py
- vivarium/utils/cobra_fba.py
Minor tweaks to the metabolism plot, which will be used in the paper.
> Metabolism plots

- vivarium/composites/master.py
this updates the master composite with the recent complexation process, and also upgrades the BiGG metabolism.
> update master with complexation, bigger BiGG metabolism

- vivarium/composites/master.py
This completes #195. Update master with the appropriate configs.
> update master with config

- vivarium/processes/multibody_physics.py
This adds a pygame debug screen to the multi body process. If you run multi body on its own, this screen will come up and you can see the agents moving around live. This makes debugging much easier, as you can see the outcome of changes come to life in front of you.  Many of the figures were also tweaked.
> multibody motility debug screen

- vivarium/compartment/emitter.py
- vivarium/composites/flagella_expression.py
- vivarium/composites/glc_lct_shifter.py
- vivarium/composites/txp_mtb_ge.py
- vivarium/parameters/parameters.py
- vivarium/processes/division.py
This revamps the ```parameter_scan``` function, adding the option to scan in different conditions, and reworking the plot summary. The figure below shows a parameter scan of 2 parameters in 2 conditions for a transport-metabolism-gene_expression composite. Scanned parameters include k_cats for glucose and lactose exchange reactions; conditions include glucose media and lactose media. I will do a more thorough scan of this compartment in the next PR -- this PR is just to add the new functionality.
> Improved parameter scanning

- vivarium/processes/multibody_physics.py
This adds snapshot output plots to all runs in ```multibody```.
> multibody snapshot output

- vivarium/processes/toxin-antitoxin.py
This adds @tgillies toxin-antitoxin prototype ```mazEF_separate_TE``` from a branch in wcEcoli.  Thanks, Taryn for sharing this!  I'm not exactly sure how to interpret the output (below), but it seems to match the output from the prototype.
> toxin-antitoxin process

- vivarium/composites/flagella_expression.py
- vivarium/composites/gene_expression.py
This adds complexes to the gene expression network.  I'm still not happy with the layout, but am putting off dealing with it for a bit longer.
> Complex in expression network

- vivarium/processes/derive_globals.py
- vivarium/processes/multibody_physics.py
This initializes the test cells for ```multibody_physics``` with a more accurate length/width/volume, and also adds a function to calculate surface area.
> improve test cells length/width

- vivarium/analysis/snapshots.py
This adds more fluorescent colors to the ```snapshots``` plot.  The fig below shows wcEcoli with various tagged proteins.
> Snapshot fluorescence

- vivarium/compartment/composition.py
- vivarium/compartment/emitter.py
- vivarium/compartment/process.py
- vivarium/composites/antibiotics.py
- vivarium/composites/chemotaxis_master
- vivarium/composites/chemotaxis_minimal.py
- vivarium/composites/flagella_expression.py
- vivarium/composites/gene_expression.py
- vivarium/composites/growth_division.py
- vivarium/composites/lattice_environment.py
- vivarium/composites/master.py
- vivarium/composites/txp_mtb_ge.py
- vivarium/environment/lattice_compartment.py
- vivarium/processes/death.py
This removes all ```process_layers```, makes them all into dictionaries, and fixes all built-in assumptions of there being ```process_layers```.
> remove all process_layers

- vivarium/composites/glc_lct_shifter.py
- vivarium/processes/ode_expression.py
This adjusts the expression rate of LacY to make nice-looking response when glucose runs out:
> glc-lcts shifter test

- vivarium/analysis/snapshots.py
this fixes errors in plotting snapshot fields, which were introduced in #214.
> fix fields plot

- vivarium/core/process.py
- vivarium/processes/template_process.py
This adds more function to the template process, which will hopefully help users get their own processes set up.
> make template process run

- vivarium/compartments/chemotaxis_variable_flagella.py
- vivarium/core/composition.py
- vivarium/experiments/chemotaxis.py
- vivarium/library/pymunk_multibody.py
- vivarium/plots/multibody_physics.py
- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/meta_division.py
- vivarium/processes/metabolism.py
- vivarium/processes/multibody_physics.py
This adds a chemotaxis experiment that combines chemotactic agents with agents that have only motors but no receptors.  I've also added a new function in ```composition``` called ```agent_environment_experiment``` that makes experiments with agent and environmental compartments by configuration -- inspired in part by a composition function started by @U8NWXD on a separate branch.
> Chemotaxis mixed experiments

- vivarium/compartments/chemotaxis_master.py
- vivarium/compartments/chemotaxis_variable_flagella.py
- vivarium/compartments/transport_metabolism.py
- vivarium/core/composition.py
- vivarium/core/emitter.py
- vivarium/core/experiment.py
- vivarium/experiments/chemotaxis.py
- vivarium/plots/Mears2014_flagella_activity.py
- vivarium/plots/multibody_physics.py
- vivarium/processes/Endres2006_chemoreceptor.py
- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/Vladimirov2008_motor.py
- vivarium/processes/metabolism.py
- vivarium/processes/nonspatial_environment.py
- vivarium/processes/ode_expression.py
-```Mears2014_flagella_activity``` now has flagella as sub compartments, with a glob schema ['*'] for the flagella store -- just like agents in ```multibody_physics```/```diffusion_field```.  
- plotting option to rotate trajectory plots by 90 degreee
- ```timeseries_from_data_old ``` is completely removed.
- There is also some clean up of topologies and processes
> Flagella as subcompartments

- setup.py
- vivarium/core/composition.py
- vivarium/core/experiment.py
- vivarium/plots/multibody_physics.py
- vivarium/processes/diffusion_field.py
This PR includes improvements to Vivarium that I've uncovered while working on simulating a wcEcoli colony.
> Improvements Inspired by wcEcoli-Vivarium Integration

- vivarium/compartments/transport_metabolism.py
- vivarium/core/experiment.py
- vivarium/library/dict_utils.py
- vivarium/processes/Mears2014_flagella_activity.py
- vivarium/processes/diffusion_field.py
- vivarium/processes/metabolism.py
- vivarium/processes/ode_expression.py
- vivarium/processes/timeline.py
This PR includes fixes for topologies and other glitchy behavior. 
- '_add' updates from #239 are improved to apply_subschemas for whole hierarchy.
- if topology and ports_schema don't align, an exception is raised
- metabolism uses the configured flux_bounds, which return transport_metabolism to normal looking growth.
> Various fixes

- vivarium/core/composition.py
- vivarium/core/experiment.py
I forgot to push some commits from #238. This has the rest
> Improvements from wcEcoli, Part 2

- vivarium/core/composition.py
- vivarium/core/experiment.py
* Changes timeseries functions to work with divider data
* Update docs for `_divider`
> wcEcoli Fixes 2

- vivarium/analysis/analyze.py
- vivarium/core/emitter.py
This lets us run analyses on a remote MongoDB instance
> Allow Specifying MongoDB Host in Analysis Script

- vivarium/processes/multibody_physics.py
@U8NWXD -- let's use this opportunity to get me trained on docstring formatting. What do you think of ```multibody_physics's``` updated docstring?
> multibody docstring

- vivarium/library/pymunk_multibody.py
- vivarium/processes/multibody_physics.py
This fixes the updates in the ```multibody``` process' tests to use the new invoke update method from experiment.
> multibody tests use invoke update

- vivarium/core/composition.py
- vivarium/experiments/colony_metrics_experiment.py
- vivarium/plots/multibody_physics.py
This is a mix of fixes:
* Allow use of multiprocessing with the `agent_environment_experiment` function
* Add x-axes to multigen agent plots
* Add molecule/field names back to snapshots and tags plots
* Increase contrast of tag plots
* Change colony metrics experiment to use wcEcoli growth rate
> Multiprocessing Support in Composition Function and Plot Fixes

- vivarium/analysis/analyze.py
- vivarium/plots/multibody_physics.py
Allow including/excluding fields from snapshots and add colony metrics analysis
> Add analyses

- setup.py
Since the actor directory was removed in #282, we need to remove it from `setup.py`
> Remove now deleted actor dir from setup.py

- vivarium/core/composition.py
This depends on #287 
Adds a setting to `agent_environment_experiment` to set the experiment emit step so that wcEcoli colony sims can reduce emission frequency
> Composition emit step

- vivarium/processes/convenience_kinetics.py
- vivarium/processes/diffusion_cell_environment.py
Miscellaneous fixes to diffusion and convenience kinetics processes
> Process fixes

- vivarium/core/composition.py
- vivarium/plots/colonies.py
Allow configuring axis label, tick label, and scientific notation (offset) font sizes in multigen and colony plot functions
> Set Font Sizes for Multigen and Colony Plots

- vivarium/analysis/analyze.py
- vivarium/core/process.py
- vivarium/plots/multibody_physics.py
Changes
=======
* Remove axis ticks from snapshot and tag plots
* Add colorbar to tags plot
* Label colorbar with title
* Make field and tag labels horizontal (font size is also configurable)
Examples
=======
Example tags plot:
Example snapshots plot:
> Polish Plots

- vivarium/plots/multibody_physics.py
We tell whether a cell is dead by checking its (boundary, dead) variable.
Example:
> Color Dead Cells Black in Snapshots

- vivarium/processes/derive_globals.py
- vivarium/processes/diffusion_cell_environment_ficks.py
The literature often gives a single permeability value for the membrane. This process can model diffusion using that parameter.
> Create Ficks Diffusion Process
